declare const _default: import("../classtypes.js").Merge<import("../classtypes.js").BaseInstance, {
    ZoneSelect: import("../classtypes.js").LuCIClass<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").BaseInstance, {
        title: any;
        description: any;
        children: any;
        __init__(title: any, description: any): void;
        append(obj: AbstractElement): void;
        parse(...args: any[]): Promise<void>;
        render(): Node | Promise<Node>;
        loadChildren(...args: any[]): Promise<any>;
        renderChildren(tab_name: string, ...args: any[]): Promise<any>;
        stripTags(s: string): string;
        titleFn(attr: string, ...args: string[]): string | null;
    }>, {
        section: any;
        option: any;
        map: any;
        config: any;
        deps: any;
        initial: any;
        rmempty: boolean;
        default: any;
        size: any;
        optional: boolean;
        retain: boolean;
        datatype: string;
        validate(...args: any[]): any;
        uciconfig: string;
        ucisection: string;
        ucioption: string;
        editable: boolean;
        modalonly: boolean;
        readonly: boolean;
        width: number | string;
        onchange: ((...args: any[]) => any);
        __init__(map: any, section: any, option: any, ...args: any[]): void;
        depends(field: string | {
            [x: string]: string | RegExp;
        }, value?: string | RegExp): void;
        transformDepList(section_id: string, deplist: string[]): string[];
        transformChoices(): object;
        checkDepends(section_id: string): boolean;
        updateDefaultValue(section_id: string): void;
        cbid(section_id: string): string;
        load(section_id: string): any | Promise<any>;
        getUIElement(section_id: string): LuCI.ui.AbstractElement | null;
        cfgvalue(section_id: string, set_value: string, ...args: any[]): any;
        formvalue(section_id: string): any;
        textvalue(section_id: string): string;
        getValidator(section_id: string): () => any;
        isValid(section_id: string): boolean;
        getValidationError(section_id: string): string;
        isActive(section_id: string): boolean;
        setActive(section_id: string, active: boolean): boolean;
        triggerValidation(section_id: string): boolean;
        parse(section_id: string): Promise<void>;
        write(section_id: string, formvalue: string | string[]): null;
        remove(section_id: string): void;
    }>, {
        password: boolean;
        placeholder: string;
        __name__: string;
        value(key: string, val: Node | string): void;
        render(option_index: any, section_id: any, in_table: any): Promise<any>;
        handleValueChange(section_id: string, state: object, ev: Event): null;
        renderFrame(section_id: string, in_table: string, option_index: number, nodes: Node[]): Node;
        renderWidget(section_id: string, option_index: number, cfgvalue: string): Node;
    }>, {
        widget: string;
        orientation: string;
        deplist: any;
        size: number;
        __name__: string;
        __init__(...args: any[]): void;
        renderWidget(section_id: string, option_index: number, cfgvalue: string): Node;
    }>, {
        __name__: string;
        load(section_id: any): Promise<any>;
        filter(section_id: any, value: any): true;
        lookupZone(name: any): any;
        lookupNetwork(name: any): any;
        renderWidget(section_id: any, option_index: any, cfgvalue: any): Node;
    }>>;
    ZoneForwards: import("../classtypes.js").LuCIClass<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").BaseInstance, {
        title: any;
        description: any;
        children: any;
        __init__(title: any, description: any): void;
        append(obj: AbstractElement): void;
        parse(...args: any[]): Promise<void>;
        render(): Node | Promise<Node>;
        loadChildren(...args: any[]): Promise<any>;
        renderChildren(tab_name: string, ...args: any[]): Promise<any>;
        stripTags(s: string): string;
        titleFn(attr: string, ...args: string[]): string | null;
    }>, {
        section: any;
        option: any;
        map: any;
        config: any;
        deps: any;
        initial: any;
        rmempty: boolean;
        default: any;
        size: any;
        optional: boolean;
        retain: boolean;
        datatype: string;
        validate(...args: any[]): any;
        uciconfig: string;
        ucisection: string;
        ucioption: string;
        editable: boolean;
        modalonly: boolean;
        readonly: boolean;
        width: number | string;
        onchange: ((...args: any[]) => any);
        __init__(map: any, section: any, option: any, ...args: any[]): void;
        depends(field: string | {
            [x: string]: string | RegExp;
        }, value?: string | RegExp): void;
        transformDepList(section_id: string, deplist: string[]): string[];
        transformChoices(): object;
        checkDepends(section_id: string): boolean;
        updateDefaultValue(section_id: string): void;
        cbid(section_id: string): string;
        load(section_id: string): any | Promise<any>;
        getUIElement(section_id: string): LuCI.ui.AbstractElement | null;
        cfgvalue(section_id: string, set_value: string, ...args: any[]): any;
        formvalue(section_id: string): any;
        textvalue(section_id: string): string;
        getValidator(section_id: string): () => any;
        isValid(section_id: string): boolean;
        getValidationError(section_id: string): string;
        isActive(section_id: string): boolean;
        setActive(section_id: string, active: boolean): boolean;
        triggerValidation(section_id: string): boolean;
        parse(section_id: string): Promise<void>;
        write(section_id: string, formvalue: string | string[]): null;
        remove(section_id: string): void;
    }>, {
        password: boolean;
        placeholder: string;
        __name__: string;
        value(key: string, val: Node | string): void;
        render(option_index: any, section_id: any, in_table: any): Promise<any>;
        handleValueChange(section_id: string, state: object, ev: Event): null;
        renderFrame(section_id: string, in_table: string, option_index: number, nodes: Node[]): Node;
        renderWidget(section_id: string, option_index: number, cfgvalue: string): Node;
    }>, {
        href: string;
        rawhtml: boolean;
        hidden: boolean;
        __name__: string;
        renderWidget(section_id: string, option_index: number, cfgvalue: string): Node;
        remove(): void;
        write(): void;
    }>, {
        __name__: string;
        load(section_id: any): Promise<any>;
        renderZone(zone: any): HTMLElement;
        renderWidget(section_id: any, option_index: any, cfgvalue: any): HTMLElement;
    }>>;
    IPSelect: import("../classtypes.js").LuCIClass<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").BaseInstance, {
        title: any;
        description: any;
        children: any;
        __init__(title: any, description: any): void;
        append(obj: AbstractElement): void;
        parse(...args: any[]): Promise<void>;
        render(): Node | Promise<Node>;
        loadChildren(...args: any[]): Promise<any>;
        renderChildren(tab_name: string, ...args: any[]): Promise<any>;
        stripTags(s: string): string;
        titleFn(attr: string, ...args: string[]): string | null;
    }>, {
        section: any;
        option: any;
        map: any;
        config: any;
        deps: any;
        initial: any;
        rmempty: boolean;
        default: any;
        size: any;
        optional: boolean;
        retain: boolean;
        datatype: string;
        validate(...args: any[]): any;
        uciconfig: string;
        ucisection: string;
        ucioption: string;
        editable: boolean;
        modalonly: boolean;
        readonly: boolean;
        width: number | string;
        onchange: ((...args: any[]) => any);
        __init__(map: any, section: any, option: any, ...args: any[]): void;
        depends(field: string | {
            [x: string]: string | RegExp;
        }, value?: string | RegExp): void;
        transformDepList(section_id: string, deplist: string[]): string[];
        transformChoices(): object;
        checkDepends(section_id: string): boolean;
        updateDefaultValue(section_id: string): void;
        cbid(section_id: string): string;
        load(section_id: string): any | Promise<any>;
        getUIElement(section_id: string): LuCI.ui.AbstractElement | null;
        cfgvalue(section_id: string, set_value: string, ...args: any[]): any;
        formvalue(section_id: string): any;
        textvalue(section_id: string): string;
        getValidator(section_id: string): () => any;
        isValid(section_id: string): boolean;
        getValidationError(section_id: string): string;
        isActive(section_id: string): boolean;
        setActive(section_id: string, active: boolean): boolean;
        triggerValidation(section_id: string): boolean;
        parse(section_id: string): Promise<void>;
        write(section_id: string, formvalue: string | string[]): null;
        remove(section_id: string): void;
    }>, {
        password: boolean;
        placeholder: string;
        __name__: string;
        value(key: string, val: Node | string): void;
        render(option_index: any, section_id: any, in_table: any): Promise<any>;
        handleValueChange(section_id: string, state: object, ev: Event): null;
        renderFrame(section_id: string, in_table: string, option_index: number, nodes: Node[]): Node;
        renderWidget(section_id: string, option_index: number, cfgvalue: string): Node;
    }>, {
        widget: string;
        orientation: string;
        deplist: any;
        size: number;
        __name__: string;
        __init__(...args: any[]): void;
        renderWidget(section_id: string, option_index: number, cfgvalue: string): Node;
    }>, {
        __name__: string;
        load(section_id: any): Promise<any>;
        filter(section_id: any, value: any): true;
        renderIfaceBadge(device: any, ip: any): HTMLElement;
        renderWidget(section_id: any, option_index: any, cfgvalue: any): Node;
        textvalue(section_id: any): HTMLElement;
    }>>;
    NetworkSelect: import("../classtypes.js").LuCIClass<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").BaseInstance, {
        title: any;
        description: any;
        children: any;
        __init__(title: any, description: any): void;
        append(obj: AbstractElement): void;
        parse(...args: any[]): Promise<void>;
        render(): Node | Promise<Node>;
        loadChildren(...args: any[]): Promise<any>;
        renderChildren(tab_name: string, ...args: any[]): Promise<any>;
        stripTags(s: string): string;
        titleFn(attr: string, ...args: string[]): string | null;
    }>, {
        section: any;
        option: any;
        map: any;
        config: any;
        deps: any;
        initial: any;
        rmempty: boolean;
        default: any;
        size: any;
        optional: boolean;
        retain: boolean;
        datatype: string;
        validate(...args: any[]): any;
        uciconfig: string;
        ucisection: string;
        ucioption: string;
        editable: boolean;
        modalonly: boolean;
        readonly: boolean;
        width: number | string;
        onchange: ((...args: any[]) => any);
        __init__(map: any, section: any, option: any, ...args: any[]): void;
        depends(field: string | {
            [x: string]: string | RegExp;
        }, value?: string | RegExp): void;
        transformDepList(section_id: string, deplist: string[]): string[];
        transformChoices(): object;
        checkDepends(section_id: string): boolean;
        updateDefaultValue(section_id: string): void;
        cbid(section_id: string): string;
        load(section_id: string): any | Promise<any>;
        getUIElement(section_id: string): LuCI.ui.AbstractElement | null;
        cfgvalue(section_id: string, set_value: string, ...args: any[]): any;
        formvalue(section_id: string): any;
        textvalue(section_id: string): string;
        getValidator(section_id: string): () => any;
        isValid(section_id: string): boolean;
        getValidationError(section_id: string): string;
        isActive(section_id: string): boolean;
        setActive(section_id: string, active: boolean): boolean;
        triggerValidation(section_id: string): boolean;
        parse(section_id: string): Promise<void>;
        write(section_id: string, formvalue: string | string[]): null;
        remove(section_id: string): void;
    }>, {
        password: boolean;
        placeholder: string;
        __name__: string;
        value(key: string, val: Node | string): void;
        render(option_index: any, section_id: any, in_table: any): Promise<any>;
        handleValueChange(section_id: string, state: object, ev: Event): null;
        renderFrame(section_id: string, in_table: string, option_index: number, nodes: Node[]): Node;
        renderWidget(section_id: string, option_index: number, cfgvalue: string): Node;
    }>, {
        widget: string;
        orientation: string;
        deplist: any;
        size: number;
        __name__: string;
        __init__(...args: any[]): void;
        renderWidget(section_id: string, option_index: number, cfgvalue: string): Node;
    }>, {
        __name__: string;
        load(section_id: any): Promise<any>;
        filter(section_id: any, value: any): true;
        renderIfaceBadge(network: any): HTMLElement;
        renderWidget(section_id: any, option_index: any, cfgvalue: any): Node;
        textvalue(section_id: any): HTMLElement;
    }>>;
    DeviceSelect: import("../classtypes.js").LuCIClass<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").BaseInstance, {
        title: any;
        description: any;
        children: any;
        __init__(title: any, description: any): void;
        append(obj: AbstractElement): void;
        parse(...args: any[]): Promise<void>;
        render(): Node | Promise<Node>;
        loadChildren(...args: any[]): Promise<any>;
        renderChildren(tab_name: string, ...args: any[]): Promise<any>;
        stripTags(s: string): string;
        titleFn(attr: string, ...args: string[]): string | null;
    }>, {
        section: any;
        option: any;
        map: any;
        config: any;
        deps: any;
        initial: any;
        rmempty: boolean;
        default: any;
        size: any;
        optional: boolean;
        retain: boolean;
        datatype: string;
        validate(...args: any[]): any;
        uciconfig: string;
        ucisection: string;
        ucioption: string;
        editable: boolean;
        modalonly: boolean;
        readonly: boolean;
        width: number | string;
        onchange: ((...args: any[]) => any);
        __init__(map: any, section: any, option: any, ...args: any[]): void;
        depends(field: string | {
            [x: string]: string | RegExp;
        }, value?: string | RegExp): void;
        transformDepList(section_id: string, deplist: string[]): string[];
        transformChoices(): object;
        checkDepends(section_id: string): boolean;
        updateDefaultValue(section_id: string): void;
        cbid(section_id: string): string;
        load(section_id: string): any | Promise<any>;
        getUIElement(section_id: string): LuCI.ui.AbstractElement | null;
        cfgvalue(section_id: string, set_value: string, ...args: any[]): any;
        formvalue(section_id: string): any;
        textvalue(section_id: string): string;
        getValidator(section_id: string): () => any;
        isValid(section_id: string): boolean;
        getValidationError(section_id: string): string;
        isActive(section_id: string): boolean;
        setActive(section_id: string, active: boolean): boolean;
        triggerValidation(section_id: string): boolean;
        parse(section_id: string): Promise<void>;
        write(section_id: string, formvalue: string | string[]): null;
        remove(section_id: string): void;
    }>, {
        password: boolean;
        placeholder: string;
        __name__: string;
        value(key: string, val: Node | string): void;
        render(option_index: any, section_id: any, in_table: any): Promise<any>;
        handleValueChange(section_id: string, state: object, ev: Event): null;
        renderFrame(section_id: string, in_table: string, option_index: number, nodes: Node[]): Node;
        renderWidget(section_id: string, option_index: number, cfgvalue: string): Node;
    }>, {
        widget: string;
        orientation: string;
        deplist: any;
        size: number;
        __name__: string;
        __init__(...args: any[]): void;
        renderWidget(section_id: string, option_index: number, cfgvalue: string): Node;
    }>, {
        __name__: string;
        load(section_id: any): Promise<any>;
        filter(section_id: any, value: any): true;
        renderWidget(section_id: any, option_index: any, cfgvalue: any): Node;
    }>>;
    UserSelect: import("../classtypes.js").LuCIClass<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").BaseInstance, {
        title: any;
        description: any;
        children: any;
        __init__(title: any, description: any): void;
        append(obj: AbstractElement): void;
        parse(...args: any[]): Promise<void>;
        render(): Node | Promise<Node>;
        loadChildren(...args: any[]): Promise<any>;
        renderChildren(tab_name: string, ...args: any[]): Promise<any>;
        stripTags(s: string): string;
        titleFn(attr: string, ...args: string[]): string | null;
    }>, {
        section: any;
        option: any;
        map: any;
        config: any;
        deps: any;
        initial: any;
        rmempty: boolean;
        default: any;
        size: any;
        optional: boolean;
        retain: boolean;
        datatype: string;
        validate(...args: any[]): any;
        uciconfig: string;
        ucisection: string;
        ucioption: string;
        editable: boolean;
        modalonly: boolean;
        readonly: boolean;
        width: number | string;
        onchange: ((...args: any[]) => any);
        __init__(map: any, section: any, option: any, ...args: any[]): void;
        depends(field: string | {
            [x: string]: string | RegExp;
        }, value?: string | RegExp): void;
        transformDepList(section_id: string, deplist: string[]): string[];
        transformChoices(): object;
        checkDepends(section_id: string): boolean;
        updateDefaultValue(section_id: string): void;
        cbid(section_id: string): string;
        load(section_id: string): any | Promise<any>;
        getUIElement(section_id: string): LuCI.ui.AbstractElement | null;
        cfgvalue(section_id: string, set_value: string, ...args: any[]): any;
        formvalue(section_id: string): any;
        textvalue(section_id: string): string;
        getValidator(section_id: string): () => any;
        isValid(section_id: string): boolean;
        getValidationError(section_id: string): string;
        isActive(section_id: string): boolean;
        setActive(section_id: string, active: boolean): boolean;
        triggerValidation(section_id: string): boolean;
        parse(section_id: string): Promise<void>;
        write(section_id: string, formvalue: string | string[]): null;
        remove(section_id: string): void;
    }>, {
        password: boolean;
        placeholder: string;
        __name__: string;
        value(key: string, val: Node | string): void;
        render(option_index: any, section_id: any, in_table: any): Promise<any>;
        handleValueChange(section_id: string, state: object, ev: Event): null;
        renderFrame(section_id: string, in_table: string, option_index: number, nodes: Node[]): Node;
        renderWidget(section_id: string, option_index: number, cfgvalue: string): Node;
    }>, {
        widget: string;
        orientation: string;
        deplist: any;
        size: number;
        __name__: string;
        __init__(...args: any[]): void;
        renderWidget(section_id: string, option_index: number, cfgvalue: string): Node;
    }>, {
        __name__: string;
        load(section_id: any): any;
        filter(section_id: any, value: any): true;
    }>>;
    GroupSelect: import("../classtypes.js").LuCIClass<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").Merge<import("../classtypes.js").BaseInstance, {
        title: any;
        description: any;
        children: any;
        __init__(title: any, description: any): void;
        append(obj: AbstractElement): void;
        parse(...args: any[]): Promise<void>;
        render(): Node | Promise<Node>;
        loadChildren(...args: any[]): Promise<any>;
        renderChildren(tab_name: string, ...args: any[]): Promise<any>;
        stripTags(s: string): string;
        titleFn(attr: string, ...args: string[]): string | null;
    }>, {
        section: any;
        option: any;
        map: any;
        config: any;
        deps: any;
        initial: any;
        rmempty: boolean;
        default: any;
        size: any;
        optional: boolean;
        retain: boolean;
        datatype: string;
        validate(...args: any[]): any;
        uciconfig: string;
        ucisection: string;
        ucioption: string;
        editable: boolean;
        modalonly: boolean;
        readonly: boolean;
        width: number | string;
        onchange: ((...args: any[]) => any);
        __init__(map: any, section: any, option: any, ...args: any[]): void;
        depends(field: string | {
            [x: string]: string | RegExp;
        }, value?: string | RegExp): void;
        transformDepList(section_id: string, deplist: string[]): string[];
        transformChoices(): object;
        checkDepends(section_id: string): boolean;
        updateDefaultValue(section_id: string): void;
        cbid(section_id: string): string;
        load(section_id: string): any | Promise<any>;
        getUIElement(section_id: string): LuCI.ui.AbstractElement | null;
        cfgvalue(section_id: string, set_value: string, ...args: any[]): any;
        formvalue(section_id: string): any;
        textvalue(section_id: string): string;
        getValidator(section_id: string): () => any;
        isValid(section_id: string): boolean;
        getValidationError(section_id: string): string;
        isActive(section_id: string): boolean;
        setActive(section_id: string, active: boolean): boolean;
        triggerValidation(section_id: string): boolean;
        parse(section_id: string): Promise<void>;
        write(section_id: string, formvalue: string | string[]): null;
        remove(section_id: string): void;
    }>, {
        password: boolean;
        placeholder: string;
        __name__: string;
        value(key: string, val: Node | string): void;
        render(option_index: any, section_id: any, in_table: any): Promise<any>;
        handleValueChange(section_id: string, state: object, ev: Event): null;
        renderFrame(section_id: string, in_table: string, option_index: number, nodes: Node[]): Node;
        renderWidget(section_id: string, option_index: number, cfgvalue: string): Node;
    }>, {
        widget: string;
        orientation: string;
        deplist: any;
        size: number;
        __name__: string;
        __init__(...args: any[]): void;
        renderWidget(section_id: string, option_index: number, cfgvalue: string): Node;
    }>, {
        __name__: string;
        load(section_id: any): any;
        filter(section_id: any, value: any): true;
    }>>;
}>;
export default _default;
