// Generated by build.mjs from @lends tags.
import type { Type } from './classtypes.js';
import type * as $form from './form.js';
import type * as $fs from './fs.js';
import type * as $luci from './luci.js';
import type * as $network from './network.js';
import type * as $rpc from './rpc.js';
import type * as $uci from './uci.js';
import type * as $ui from './ui.js';
import type * as $validation from './validation.js';

declare global {
	namespace LuCI {
		interface headers extends InstanceType<typeof $luci.Headers> {}
		interface response extends InstanceType<typeof $luci.Response> {}
		interface request extends Type<typeof $luci.Request> {}
		interface poll extends Type<typeof $luci.Poll> {}
		interface dom extends Type<typeof $luci.DOM> {}
		interface session extends Type<typeof $luci.Session> {}
		interface view extends InstanceType<typeof $luci.View> {}
		interface xhr extends InstanceType<typeof $luci.XHR> {}
		type requestCallbackFn = $luci.LuCI_requestCallbackFn;
		type LuCI_requestCallbackFn = $luci.LuCI_requestCallbackFn;
		interface ui extends InstanceType<typeof $ui.UI> {}
		namespace form {
			interface AbstractElement extends InstanceType<typeof $form.CBIAbstractElement> {}
			interface Map extends InstanceType<typeof $form.CBIMap> {}
			interface JSONMap extends InstanceType<typeof $form.CBIJSONMap> {}
			interface AbstractSection extends InstanceType<typeof $form.CBIAbstractSection> {}
			interface AbstractValue extends InstanceType<typeof $form.CBIAbstractValue> {}
			interface TypedSection extends InstanceType<typeof $form.CBITypedSection> {}
			interface TableSection extends InstanceType<typeof $form.CBITableSection> {}
			interface GridSection extends InstanceType<typeof $form.CBIGridSection> {}
			interface NamedSection extends InstanceType<typeof $form.CBINamedSection> {}
			interface Value extends InstanceType<typeof $form.CBIValue> {}
			interface DynamicList extends InstanceType<typeof $form.CBIDynamicList> {}
			interface ListValue extends InstanceType<typeof $form.CBIListValue> {}
			interface RichListValue extends InstanceType<typeof $form.CBIRichListValue> {}
			interface RangeSliderValue extends InstanceType<typeof $form.CBIRangeSliderValue> {}
			interface Flag extends InstanceType<typeof $form.CBIFlagValue> {}
			interface MultiValue extends InstanceType<typeof $form.CBIMultiValue> {}
			interface TextValue extends InstanceType<typeof $form.CBITextValue> {}
			interface DummyValue extends InstanceType<typeof $form.CBIDummyValue> {}
			interface Button extends InstanceType<typeof $form.CBIButtonValue> {}
			interface HiddenValue extends InstanceType<typeof $form.CBIHiddenValue> {}
			interface FileUpload extends InstanceType<typeof $form.CBIFileUpload> {}
			interface DirectoryPicker extends InstanceType<typeof $form.CBIDirectoryPicker> {}
			interface SectionValue extends InstanceType<typeof $form.CBISectionValue> {}
		}
		namespace fs {
			type FileStatEntry = $fs.FileStatEntry;
			type FileExecResult = $fs.FileExecResult;
		}
		namespace request {
			type interceptorFn = $luci.LuCI_request_interceptorFn;
			type RequestOptions = $luci.RequestOptions;
			namespace poll {
				type callbackFn = $luci.LuCI_request_poll_callbackFn;
			}
		}
		namespace dom {
			type ignoreCallbackFn = $luci.LuCI_dom_ignoreCallbackFn;
		}
		namespace network {
			type WifiEncryption = $network.LuCI_network_WifiEncryption;
			type LuCI_network_WifiEncryption = $network.LuCI_network_WifiEncryption;
			type SwitchTopology = $network.SwitchTopology;
			type WifiScanResult = $network.WifiScanResult;
			type WifiPeerEntry = $network.WifiPeerEntry;
			type WifiRateEntry = $network.WifiRateEntry;
		}
		namespace rpc {
			type filterFn = $rpc.LuCI_rpc_filterFn;
			type invokeFn = $rpc.LuCI_rpc_invokeFn;
			type interceptorFn = $rpc.LuCI_rpc_interceptorFn;
			type DeclareOptions = $rpc.DeclareOptions;
		}
		namespace uci {
			type sections = $uci.LuCI_uci_sections;
			type SectionObject = $uci.SectionObject;
			type ChangeRecord = $uci.ChangeRecord;
		}
		namespace ui {
			interface AbstractElement extends InstanceType<typeof $ui.UIElement> {}
			interface Textfield extends InstanceType<typeof $ui.UITextfield> {}
			interface Textarea extends InstanceType<typeof $ui.UITextarea> {}
			interface Checkbox extends InstanceType<typeof $ui.UICheckbox> {}
			interface Select extends InstanceType<typeof $ui.UISelect> {}
			interface Dropdown extends InstanceType<typeof $ui.UIDropdown> {}
			interface Combobox extends InstanceType<typeof $ui.UICombobox> {}
			interface ComboButton extends InstanceType<typeof $ui.UIComboButton> {}
			interface DynamicList extends InstanceType<typeof $ui.UIDynamicList> {}
			interface Hiddenfield extends InstanceType<typeof $ui.UIHiddenfield> {}
			interface FileUpload extends InstanceType<typeof $ui.UIFileUpload> {}
			interface menu extends Type<typeof $ui.UIMenu> {}
			interface table extends InstanceType<typeof $ui.UITable> {}
			type FileUploadReply = $ui.FileUploadReply;
			namespace AbstractElement {
				type InitOptions = $ui.InitOptions;
			}
			namespace Textfield {
				type InitOptions = $ui.InitOptions;
			}
			namespace Textarea {
				type InitOptions = $ui.InitOptions;
			}
			namespace Checkbox {
				type InitOptions = $ui.InitOptions;
			}
			namespace Select {
				type InitOptions = $ui.InitOptions;
			}
			namespace Dropdown {
				type InitOptions = $ui.InitOptions;
			}
			namespace Combobox {
				type InitOptions = $ui.InitOptions;
			}
			namespace ComboButton {
				type InitOptions = $ui.InitOptions;
			}
			namespace DynamicList {
				type InitOptions = $ui.InitOptions;
			}
			namespace RangeSlider {
				type InitOptions = $ui.InitOptions;
			}
			namespace FileUpload {
				type InitOptions = $ui.InitOptions;
			}
			namespace menu {
				type MenuNode = $ui.MenuNode;
			}
		}
		namespace validation {
			interface Validator extends InstanceType<typeof $validation.Validator> {}
			interface ValidatorFactory extends InstanceType<typeof $validation.ValidatorFactory> {}
		}
	}
}
